name: Test AWS deployment  

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    name: Run Deployment
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Tests
        run: ./scripts/deploy.sh  
