name: Cross Account Deployment  

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Linux]
    echo "Started the deployment"
    name: Run Deployment
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Tests
        run: ./scripts/deploy.sh  
