# This is a basic workflow to help you get started with Actions

name: addS3BucketAWS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

   # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      #- uses: actions/checkout@master
       - uses: actions/checkout@v3
         with:
            fetch-depth: 0
       - name: Run Tests
         run: 
            sudo chmod 777 ./scripts/deploy.sh
            ./scripts/deploy.sh

      # - name: Upload to S3
        # run: |
          # aws s3 mb s3://git-action-bucket-350978175498-c-2 --region us-east-1
        # env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_DEFAULT_REGION: 'us-east-1'
          # #AWS-SESSION-TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}